---
title: "Double Shutter Simluation"
output: html_document
---

```{r checkTotalExists}
## This checks if the total die roll exists in any combiantion of the existing tiles. 
checkTotalExists <- function(tiles, total){
  existsBin <- FALSE
  # for(i in 1:length(tiles)){
  #   if(i == length(tiles)) tileSums <- sum(tiles)
  #   else tileSums <- colSums(combn(tiles, i))
  #   
  #   if(total %in% tileSums) existsBin <- TRUE
  # }
  if(length(makeCombos(tiles, total)) > 0) existsBin <- T
  return(existsBin)
}

checkTotalExists(c(1), 5)
```

```{r rollDice}
## Rolls two dice; if tile total is less than 7, rolls one dice
rollDice <- function(tiles){
  if(sum(tiles) <= 6) return(sample(1:6, 1))
  else{
    return(sum(sample(1:6, 1), sample(1:6, 1)))
  }
}

## checking distribution
total <- c()
for(i in 1:5000) total[i] <- rollDice(tiles)
hist(total, breaks = 15)
```

```{r makeCombos}
makeCombos <- function(tiles, total){
    y = NULL
    ## if single element
    if(length(tiles) == 1){
      if(tiles == total) y = c(y, list(tiles))
    }
    else if(length(tiles) > 1){
        for(m in 1:(length(tiles)-1)){
        tmp = combn(tiles, m)
        ind = which(colSums(tmp) == total)
        if (length(ind) > 0){
            for (j in 1:length(ind))
                y = c(y, list(tmp[,ind[j]]))
            }
        }
      if(sum(tiles) == total) y = c(y, list(tiles))
    }

    return(unique(lapply(y, sort)))
  }

```

```{r largestTile}
## Strategy #1 - pick largest tile(s)
largestTile <- function(tiles, total){
  tilesToShut <- c()
  orderedTiles <- order(-tiles)
  
  ## if total is one of the tiles, use that
  if(total %in% tiles){
    tilesToShut <- total
    return(tilesToShut)
  }
  ## if total is sum of all tiles, use all
   if(total == sum(tiles)){
    tilesToShut <- tiles
    return(tilesToShut)
  }
  
  ## else, look at list all combos of tiles that equal the total
  ## make all combos
  combos <- makeCombos(tiles, total)
  
  ## if just one combo, return that
  if(length(combos) == 1){
     tilesToShut <- unlist(combos)
    return(tilesToShut)
  }
  
  ## loop through all combos, find one with largest element(s)
  winningComboIndex <- 1
  winningMax <- max(combos[[1]])
  for(i in 2:length(combos)){
    currentMax <- max(combos[[i]])
    if(currentMax < winningMax) next
    ## if current is bigger, swap to be winning
    if(currentMax > winningMax){
      winningMax <- currentMax
      winningComboIndex <- i
      next
    }
    if(currentMax == winningMax){ ## need to check next highest, remove ONE OF highest
      currentCombo <- combos[[i]]
      currentCombo <- currentCombo[-which(currentCombo == currentMax)[1]]
      winningCombo <- combos[[winningComboIndex]]
      winningCombo <- winningCombo[-which(winningCombo == currentMax)[1]]
      ## check next highest in set
      if(max(currentCombo) > max(winningCombo)){
        winningMax <- currentMax
        winningComboIndex <- i
        next
      }
     ## if they're even, just leave it
    }
  }

  ## subset winning combo with winningComboIndex
  tilesToShut <- combos[[winningComboIndex]]
 
  return(tilesToShut)
}

largestTile(c(1,1,4,5,2,6), 7) ## looks good
```

```{r shutTiles}

shutTiles <- function(tilesToShut, frontRow, backRow){
  ## always shut front row first!
  
  ## loop through tilesToShut
  for(i in 1:length(tilesToShut)){
    ## remove from front row first, if possible
    if(tilesToShut[i] %in% frontRow){ 
      ## remove from front row
      frontRow <- frontRow[frontRow != tilesToShut[i]]
      
      ## add newly revealed backRow tiles - always add to 10
      backRow <- c(backRow, 10 - tilesToShut[i])
    }
    ## else remove from back row
    else{
     ## remove from back row
      backRow <- backRow[backRow != tilesToShut[i]]
    }
  }
  return(list("frontRow" = frontRow, "backRow" = backRow))
}

```


```{r playGame}
playGame <- function(){
  frontRow <- c(1:9)
  backRow <- c()
  total <- rollDice(c(frontRow, backRow))
  while(checkTotalExists(c(frontRow, backRow), total)){
    
    ## strategy to determine which tiles to shut
    tilesToShut <- largestTile(c(frontRow, backRow), total)
    
    ## shutting the chosen tiles, ensuring front tiles reveal correct back tiles
    returned <- shutTiles(tilesToShut, frontRow, backRow)
    frontRow <- returned$frontRow
    backRow <- returned$backRow
    
    cat("front: ", frontRow, "back:", backRow, "total:", total,  "\n")
    
    ## re-roll to start next turn
    total <- rollDice(c(frontRow, backRow))
    
    ## check win condition
    if(length(frontRow) == 0 & length(backRow) == 0) break
  }
  #cat("front: ", frontRow, "back:", backRow, "total:", total,  "\n")
  ## game over, score is total of remaining tiles (front row is doubled)
  return(sum(backRow, (2*frontRow)))
}

```

```{r simluating games}
## 10,000 simluations of largestTile strategy
totals <- c()
for(i in 1:10000){
  cat("game ", i, "\n")
  totals <- c(totals, playGame())
}

```

